/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AspectRatio: typeof import('./src/components/container/AspectRatio.vue')['default']
    AutoHeight: typeof import('./src/components/container/AutoHeight.vue')['default']
    BaseDisplay: typeof import('./src/components/base/display/BaseDisplay.vue')['default']
    BaseEditor: typeof import('./src/components/base/editor/BaseEditor.vue')['default']
    BaseInput: typeof import('./src/components/base/input/BaseInput.vue')['default']
    BaseTree: typeof import('./src/components/base/tree/BaseTree.vue')['default']
    FullscreenContainer: typeof import('./src/components/container/FullscreenContainer.vue')['default']
    LazyContainer: typeof import('./src/components/container/LazyContainer.vue')['default']
    LoadingContainer: typeof import('./src/components/container/LoadingContainer.vue')['default']
    PermButton: typeof import('./src/components/common/PermButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollContainer: typeof import('./src/components/container/ScrollContainer.vue')['default']
    SectionContainer: typeof import('./src/components/container/SectionContainer.vue')['default']
    VirtualList: typeof import('./src/components/container/VirtualList.vue')['default']
  }
}
