/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AspectRatio: typeof import('./src/components/container/AspectRatio.vue')['default']
    AutoHeight: typeof import('./src/components/container/AutoHeight.vue')['default']
    BaseDisplay: typeof import('./src/components/base/display/BaseDisplay.vue')['default']
    BaseEditor: typeof import('./src/components/base/editor/BaseEditor.vue')['default']
    BaseInput: typeof import('./src/components/base/input/BaseInput.vue')['default']
    BaseTree: typeof import('./src/components/base/tree/BaseTree.vue')['default']
    Card: typeof import('./src/components/layout/Card.vue')['default']
    Collapse: typeof import('./src/components/layout/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/layout/CollapseItem.vue')['default']
    ConfirmDialog: typeof import('./src/components/modal/ConfirmDialog.vue')['default']
    Divider: typeof import('./src/components/layout/Divider.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    EmptyState: typeof import('./src/components/feedback/EmptyState.vue')['default']
    ErrorPage: typeof import('./src/components/feedback/ErrorPage.vue')['default']
    FormDialog: typeof import('./src/components/modal/FormDialog.vue')['default']
    FormDrawer: typeof import('./src/components/modal/FormDrawer.vue')['default']
    FormFrame: typeof import('./src/components/layout/FormFrame.vue')['default']
    FormFrameTabs: typeof import('./src/components/tabs/FormFrameTabs.vue')['default']
    FullscreenContainer: typeof import('./src/components/container/FullscreenContainer.vue')['default']
    GridCol: typeof import('./src/components/layout/GridCol.vue')['default']
    GridRow: typeof import('./src/components/layout/GridRow.vue')['default']
    LazyContainer: typeof import('./src/components/container/LazyContainer.vue')['default']
    LoadingContainer: typeof import('./src/components/container/LoadingContainer.vue')['default']
    LoadingMask: typeof import('./src/components/feedback/LoadingMask.vue')['default']
    MasterDetail: typeof import('./src/components/layout/MasterDetail.vue')['default']
    MasterTree: typeof import('./src/components/layout/MasterTree.vue')['default']
    MenuNode: typeof import('./src/components/menu/MenuNode.vue')['default']
    PageContainer: typeof import('./src/components/layout/PageContainer.vue')['default']
    PermButton: typeof import('./src/components/common/PermButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollContainer: typeof import('./src/components/container/ScrollContainer.vue')['default']
    SectionContainer: typeof import('./src/components/container/SectionContainer.vue')['default']
    SideMenu: typeof import('./src/components/menu/SideMenu.vue')['default']
    SkeletonBlock: typeof import('./src/components/feedback/SkeletonBlock.vue')['default']
    Space: typeof import('./src/components/layout/Space.vue')['default']
    Split: typeof import('./src/components/layout/Split.vue')['default']
    TabPane: typeof import('./src/components/layout/TabPane.vue')['default']
    Tabs: typeof import('./src/components/layout/Tabs.vue')['default']
    TabsNav: typeof import('./src/components/tabs/TabsNav.vue')['default']
    VirtualList: typeof import('./src/components/container/VirtualList.vue')['default']
  }
}
