/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDisplay: typeof import('./src/components/base/display/BaseDisplay.vue')['default']
    BaseEditor: typeof import('./src/components/base/editor/BaseEditor.vue')['default']
    BaseInput: typeof import('./src/components/base/input/BaseInput.vue')['default']
    BaseTree: typeof import('./src/components/base/tree/BaseTree.vue')['default']
    ConfirmDialog: typeof import('./src/components/modal/ConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    FormDialog: typeof import('./src/components/modal/FormDialog.vue')['default']
    FormDrawer: typeof import('./src/components/modal/FormDrawer.vue')['default']
    PermButton: typeof import('./src/components/common/PermButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
