/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDisplay: typeof import('./src/components/base/display/BaseDisplay.vue')['default']
    BaseEditor: typeof import('./src/components/base/editor/BaseEditor.vue')['default']
    BaseInput: typeof import('./src/components/base/input/BaseInput.vue')['default']
    BaseTree: typeof import('./src/components/base/tree/BaseTree.vue')['default']
    Card: typeof import('./src/components/layout/Card.vue')['default']
    Collapse: typeof import('./src/components/layout/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/layout/CollapseItem.vue')['default']
    ConfirmDialog: typeof import('./src/components/modal/ConfirmDialog.vue')['default']
    Divider: typeof import('./src/components/layout/Divider.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EmptyState: typeof import('./src/components/feedback/EmptyState.vue')['default']
    ErrorPage: typeof import('./src/components/feedback/ErrorPage.vue')['default']
    FormDialog: typeof import('./src/components/modal/FormDialog.vue')['default']
    FormDrawer: typeof import('./src/components/modal/FormDrawer.vue')['default']
    FormFrameTabs: typeof import('./src/components/tabs/FormFrameTabs.vue')['default']
    GridCol: typeof import('./src/components/layout/GridCol.vue')['default']
    GridRow: typeof import('./src/components/layout/GridRow.vue')['default']
    LoadingMask: typeof import('./src/components/feedback/LoadingMask.vue')['default']
    MasterDetail: typeof import('./src/components/layout/MasterDetail.vue')['default']
    MasterTree: typeof import('./src/components/layout/MasterTree.vue')['default']
    PermButton: typeof import('./src/components/common/PermButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonBlock: typeof import('./src/components/feedback/SkeletonBlock.vue')['default']
    Space: typeof import('./src/components/layout/Space.vue')['default']
    Split: typeof import('./src/components/layout/Split.vue')['default']
    TabPane: typeof import('./src/components/layout/TabPane.vue')['default']
    Tabs: typeof import('./src/components/layout/Tabs.vue')['default']
    TabsNav: typeof import('./src/components/tabs/TabsNav.vue')['default']
  }
}
