/**
 * `@bms/core`：前端框架无关核心运行时入口。
 *
 * 纯 TS，不依赖 Vue / UI 库 / 插件 / 宿主（护栏 `tests/guard-core-framework-agnostic.spec.ts`）。
 * 基类与能力导出随 `02_01` ~ `02_06` 就位后在本入口追加。
 */
export { BaseObject, configureBase, getBaseSinks, resetBaseSinks, } from './base/BaseObject';
export { BaseFrameworkObject } from './base/framework-object';
export { withBaseObject } from './base/mixin';
export { BaseComponent, } from './base/BaseComponent';
export { ErrorCodes, FRONTEND_RESERVED_SEGMENT, isFrontendReservedCode } from './mechanisms/error-codes';
export { BaseCapability } from './mechanisms/capability';
export { BasePluggable, DEFAULT_CONTRACT_VERSION } from './mechanisms/pluggable';
export { BaseError } from './mechanisms/error';
export { BaseProviderRegistry, CapabilityRegistry } from './mechanisms/registry';
export { BaseProvider } from './mechanisms/provider';
export { BaseFactory } from './mechanisms/factory';
export { BaseAsyncResource } from './mechanisms/resource';
export { BaseSubscription } from './mechanisms/subscription';
export { BaseNullObject, BasePlaceholder, BaseStub } from './mechanisms/placeholder';
export { BaseValue } from './capabilities/value';
export { BaseField } from './capabilities/field';
export { BaseSized } from './capabilities/sized';
export { BaseDataState } from './capabilities/data-state';
export { BaseChart, } from './capabilities/chart';
export { BaseReportDesigner, } from './capabilities/report-designer';
export { BaseScreenDesigner, } from './capabilities/screen-designer';
export { BaseScreenPlayer, } from './capabilities/screen-player';
export { BaseOverlay } from './capabilities/overlay';
export { BaseNotice } from './capabilities/notice';
export { BaseLabeled } from './capabilities/labeled';
export { BaseValidatable } from './capabilities/validatable';
export { assertCapabilityGraph, CAPABILITY_MANIFEST, validateCapabilityGraph, } from './capabilities/manifest';
export { BasePersistedState } from './capabilities/persisted-state';
export { BaseWizard, } from './capabilities/wizard';
export { BaseSelection } from './capabilities/selection';
export { BaseBulkAction, } from './capabilities/bulk-action';
export { BaseTheme } from './capabilities/theme';
export { BaseTenant } from './capabilities/tenant';
export { BasePrintTemplate } from './capabilities/print-template';
export { BasePrint, PRINT_JOB_PLACEHOLDER, } from './capabilities/print';
export { BasePermissionConfig, } from './capabilities/permission-config';
export { BaseMounted } from './capabilities/mounted';
export { BaseDesignToken } from './capabilities/design-token';
export { BaseClickable } from './capabilities/interactive';
export { BaseDragDrop } from './capabilities/drag-drop';
export { BaseTabs } from './capabilities/tabs';
export { BaseLocale } from './capabilities/locale';
export { BaseAccess } from './capabilities/access';
export { BaseModuleContext } from './capabilities/module-context';
export { BaseModuleApi } from './capabilities/module-api';
export { BaseAsyncTask, } from './capabilities/async-task';
export { BaseUploadEngine, } from './capabilities/upload-engine';
export { BaseUploadTransport, UploadTransportProvider, UploadTransportRegistry, } from './capabilities/upload-transport';
export { BaseFileUpload, } from './capabilities/file-upload';
export { BaseFileDownload, DOWNLOAD_PLACEHOLDER_TEXT, } from './capabilities/file-download';
export { BaseImportFlow, } from './capabilities/import-flow';
export { BaseExportFlow, } from './capabilities/export-flow';
export { BaseFormDesigner, } from './capabilities/form-designer';
export { BaseFormRenderer, } from './capabilities/form-renderer';
export { BaseMessageCatalog, } from './capabilities/message-catalog';
export { BaseApprovalFlow, } from './capabilities/approval-flow';
export { BaseProcessModeler, } from './capabilities/process-modeler';
export { BaseEditorKernel } from './capabilities/editor-kernel';
export { BaseOptionSource } from './capabilities/option-source';
export { BaseOrgSource, OrgSourceProvider, OrgSourceRegistry, } from './capabilities/org-source';
export { BasePresignedUrl } from './capabilities/presigned-url';
export { BasePlaceholderState } from './capabilities/placeholder-state';
export { BaseChartEngine, ChartEngineProvider, ChartEngineRegistry, } from './capabilities/chart-engine';
export { BaseRealtimeChannel, RealtimeChannelProvider, RealtimeChannelRegistry, } from './capabilities/realtime-channel';
export { BaseAiStream, AiStreamProvider, AiStreamRegistry } from './capabilities/ai-stream';
export { BaseSearchEngine, SearchEngineProvider, SearchEngineRegistry, } from './capabilities/search-engine';
export { BaseWatermark } from './capabilities/watermark';
export { BaseUserDisplay } from './capabilities/user-display';
export { BaseDynamicRoutes } from './capabilities/dynamic-routes';
export { BaseFormMeta } from './capabilities/form-meta';
export { BaseFormPage } from './capabilities/form-page';
export { BaseInput } from './capabilities/input';
export { BaseDisplay } from './capabilities/display';
export { BaseTable } from './capabilities/table';
export { BaseList } from './capabilities/list';
export { BaseTreeData } from './capabilities/tree-data';
export { BaseModalShell } from './capabilities/modal-shell';
export { BaseFormContainer } from './capabilities/form-container';
export { BaseContainer } from './capabilities/container';
export { BaseLayout } from './capabilities/layout';
export { BaseMediaContent } from './capabilities/media';
export { BaseFeedback } from './capabilities/feedback';
export { BaseNotificationCenter, } from './capabilities/notification-center';
export { BaseNotification } from './capabilities/notification';
export { BaseAiAssistant, } from './capabilities/ai-assistant';
export { BaseGlobalSearch } from './capabilities/global-search';
export { BaseSearch } from './capabilities/search';
export { BaseOrgSelect } from './capabilities/org-select';
export { BaseCaptchaSource, CaptchaSourceProvider, CaptchaSourceRegistry, } from './capabilities/captcha-source';
export { BaseCaptcha, } from './capabilities/captcha';
export { BaseSsoQrSource, SsoQrSourceProvider, SsoQrSourceRegistry, } from './capabilities/sso-qr-source';
export { BaseSsoQr } from './capabilities/sso-qr';
export { BaseDictSource, DictSourceProvider, DictSourceRegistry, } from './capabilities/dict-source';
export { BaseDictStore, bindDictStoreSource, } from './capabilities/dict-store';
export { BaseDictSelect } from './capabilities/dict-select';
export { BaseDictQuery } from './capabilities/dict-query';
export { BaseMultilingualName } from './capabilities/i18n-name-field';
export { BaseI18nLocaleSource, I18nLocaleSourceProvider, I18nLocaleSourceRegistry, } from './capabilities/i18n-locale-source';
export { BaseColumnConfig } from './capabilities/column-config';
export { BaseQueryScheme } from './capabilities/query-scheme';
export { BaseFieldShell } from './capabilities/field-shell';
export { BaseFieldPerm } from './capabilities/field-perm';
export { EMPTY_PLACEHOLDER, formatAmount, formatDate, formatDateTime, formatDuration, formatFileSize, formatNumber, formatPercent, formatCompactTimestamp, formatRelativeTime, mask, } from './domain/format';
export { amount, codePattern, email, lengthRange, numberRange, phone, required, url } from './domain/validators';
export { evaluatePermission } from './domain/permission';
export { DATA_SCOPE_POLICIES, EMPTY_PERMISSION_METADATA, MATCH_PATTERN_ALLOWED, PERMISSION_ERROR_TARGETS, PERMISSION_GRANT_CODE, PERMISSION_PLACEHOLDER_TEXT, PERMISSION_SOURCE_DIRECT, PERMISSION_TABS, actionSourceMenuIds, bindUsers, collectCheckedMenuIds, collectDataScopeEntries, collectDataScopePayload, collectFieldEntries, collectFieldPayload, collectPermissionPayload, deriveIdempotencyKey, diffUserIds, fieldPermOf, findFieldMismatch, findMenu, flattenMenus, formSourceMenuIds, isActionGranted, isFormGranted, isMenuDetached, isValidMatchPattern, menuCheckState, menuFormIds, menuSubtreeIds, payloadKey, pruneMenuFieldEntries, removeDataScopeEntry, resolveErrorCode, resolveErrorTarget, setDataScopeEntry, setFieldPerm, toggleAction, toggleMenu, unbindUser, } from './domain/permission-config';
export { resolveToken } from './domain/token';
export { DEFAULT_BRAND_PRIMARY, THEME_ACCENT_PRESETS, darken, deriveBrandTokens, isValidColor, lighten, luminance, mixColor, normalizeBrand, parseColor, resolveThemeMode, toHex, } from './domain/brand';
export { MAX_DECIMAL_PRECISION, compareDecimal, fromMinorUnits, isDecimal, isDecimalInRange, normalizeDecimal, sanitizePrecision, toMinorUnits, } from './domain/decimal';
export { computeVirtualRange } from './domain/virtual-range';
export { PLACEHOLDER_MENU, filterMenuByKeyword, filterMenuByPermission, findMenuByPath, flattenMenu, toRouteNodes, } from './domain/menu';
export { PREFERENCE_DEFAULTS, PREFERENCE_KEYS, applyPreferenceDefaults, diffPreferences, isPreferenceEnabled, isPreferenceVisible, mergePreferences, readPreferenceValue, resolvePreferenceDefaults, sanitizePreferences, writePreferenceValue, } from './domain/preference';
export { PAPER_SIZES, PRINT_MISSING_TEXT, PRINT_STYLE_VARS, buildPrintPages, computeRowsPerPage, distributeFields, formatCellValue, formatPageFooter, paginateRows, resolvePaperSize, resolvePrintTone, resolveRowsPerPage, sumNumeric, } from './domain/print';
export { IMPORT_ACCEPT, IMPORT_DEFAULT_MAX_SIZE, IMPORT_ERROR_DISPLAY_LIMIT, IMPORT_ERROR_PAGE_SIZE, IMPORT_FILE_ERROR_RANGE, IMPORT_PERM, IMPORT_PLACEHOLDER_TEXT, checkImportFile, deriveImportKey, errorReportFileName, fileExtension, isFileLevelError, normalizeAccept, normalizeImportResult, paginateImportErrors, resolveImportErrorText, resolveImportSummary, templateFileName, } from './domain/import';
export { EXPORT_EMPTY_TEXT, EXPORT_FILE_EXT, EXPORT_PERM, EXPORT_PLACEHOLDER_TEXT, EXPORT_PLAIN_PERM, EXPORT_QUEUED_TEXT, canExportPlain, exportErrorMessage, exportFileName, normalizeExportParams, normalizeSelectedIds, resolveExportDecision, resolveExportMode, } from './domain/export';
export {} from './module/types';
export { MODULE_NAME_PATTERN, defineModule } from './module/define';
export { MODULE_CONTRACT_VERSION } from './module/contract';
export { DEFAULT_LOAD_MODE, LOAD_MODES, REMOTE_ENTRY_PATTERN, parseModuleManifest, } from './module/manifest';
export { applyThemeTokens, collectThemeTokens, releaseThemeTokens, } from './module/theme-tokens';
export { ModuleMessageStore } from './module/i18n-packs';
export { MODULE_LOAD_TIMEOUT_MS, PLATFORM_MODULE_NAME, } from './module/telemetry';
export { BaseModuleTelemetry, ModuleTelemetry } from './capabilities/module-telemetry';
export { BaseModuleReporter, InMemoryModuleReporter, ModuleReporterProvider, ModuleReporterRegistry, } from './capabilities/module-reporter';
export { ComponentProvider, ComponentRegistry, FieldRendererProvider, FieldRendererRegistry, I18nPackProvider, I18nPackRegistry, IconProvider, IconRegistry, ICON_KEY_PATTERN, LOCALE_TAG_PATTERN, NAMED_SLOT_ID_PATTERN, PAGE_AREA_ID_PATTERN, PageAreaProvider, PageAreaRegistry, REGISTRY_KEY_PATTERN, RouteMenuProvider, RouteMenuRegistry, ThemeTokenProvider, ThemeTokenRegistry, WorkbenchCardProvider, WorkbenchCardRegistry, assertIconKey, assertLocaleTag, assertNamespacedKey, assertPageAreaId, createRegistries, schemaError, } from './registries';
export { PLATFORM_SOURCE, assembleRegistrations, releaseRegistrations, } from './registries/assemble';
export { MODULE_EXPOSE_KEY, MODULE_REMOTE_ENTRY_FILE, ManifestModuleLoader, createModuleEntryTableResolver, remoteEntryUrl, } from './module/loader';
export { BaseApi } from './contracts/api';
export { API_VERSION_SEGMENT, PRODUCT_KEYS, SERVICE_KEYS, isProductKey, isServiceKey, productDomain, productPrefix, productUrl, servicePrefix, serviceUrl, } from './contracts/service-endpoint';
export { DEFAULT_FORBIDDEN_PATH, DEFAULT_HOME_PATH, DEFAULT_LOGIN_PATH, DEFAULT_PUBLIC_PATHS, REDIRECT_QUERY_KEY, buildLoginLocation, isPublicPath, resolveAuthGuard, resolveAuthRedirect, resolveSafeRedirect, } from './domain/route-guard';
export { configureRequestAdapter, getRequestAdapter, request, } from './contracts/request';
export {} from './contracts/module-api';
export { BaseDataObject } from './contracts/data-object';
export { BaseEntity } from './contracts/entity';
export { BasePageQuery } from './contracts/page-query';
export { DEFAULT_LABEL_WIDTH, DEFAULT_LAYOUT_COLUMNS, DEFAULT_SECTION_KEY, DESIGNER_EMPTY_HINT, DESIGNER_PLACEHOLDER_TEXT, DETAIL_WIDTH_RANGE, EXT_COLUMN_PREFIX, EXT_FIELD_TYPES, EXT_OPTION_TYPES, FORMDESIGN_PERM, FORMDESIGN_VIEW_PERM, LABEL_WIDTH_RANGE, SECTION_COLUMNS, SECTION_FIELD_HINT, SECTION_KEY_PREFIX, addSection, canDragField, checkExtField, collectFieldKeys, countLayoutFields, defaultLayout, emptyLayout, extColumnName, extFieldNeedsOptions, findDisabledFields, findDuplicateFields, findSection, findUnknownFields, hasField, insertField, isLayoutDirty, isLayoutEmpty, layoutEqual, locateField, moveField, newSectionKey, normalizeColumns, normalizeFieldRef, normalizeFieldRefs, normalizeLayout, normalizeSelection, removeField, removeSection, renameSection, resolveEffectiveLayout, resolveExtDdlStatus, resolveLayoutForLevel, resolveLevelReadOnly, resolveRestoreTarget, setDetailColumns, setLabelPosition, setLabelWidth, setQueryFields, setSectionColumns, toRenderMetadata, toggleColSpan, validateLayout, } from './domain/form-layout';
export { buildChartOption, buildChartTheme, chartConfigEqual, chartKindOption, chartOptionSignature, CHART_AXIS_TOKEN, CHART_CACHE_TTL, CHART_COLOR_FALLBACK, CHART_COLOR_TOKENS, CHART_CONFIG_VERSION, CHART_EMPTY_TEXT, CHART_GRID_TOKEN, CHART_KINDS, CHART_PLACEHOLDER_TEXT, CHART_RESIZE_INTERVAL, CHART_TEXT_TOKEN, CHART_TOOLTIP_BG_TOKEN, CHART_TOOLTIP_TEXT_TOKEN, CHART_VIEW_PERM, deepMerge, defaultMapping, emptyMapping, hasChartAxis, isChartEmpty, isMappingEmpty, isNumericField, mergeChartOption, normalizeChartConfig, normalizeChartKind, normalizeMapping, resolveChartMode, rotatePalette, serializeChartConfig, shouldReplaceOption, shouldResize, toNumber, } from './domain/chart';
export { addChartItem, buildItemConfig, centerChartItem, collectUsedDatasets, countCharts, datasetOptions, duplicateChartItem, fieldsOf, findChartItem, hasOverlap, isReportDirty, moveChartItem, nextChartId, normalizeCell, normalizeChartItem, normalizeReportCharts, removeChartItem, reportChartsEqual, resizeChartItem, resolveChartTitle, serializeChartConfigs, serializeReport, serializeReportLayout, updateChartItem, validateReport, REPORT_DEFAULT_CELL, REPORT_DESIGN_PERM, REPORT_DESIGNER_PLACEHOLDER_TEXT, REPORT_GRID_COLUMNS, REPORT_MAX_CELL, REPORT_MIN_CELL, REPORT_VIEW_PERM, } from './domain/report-layout';
export { addComponent, addPage, bringToTop, canvasStyle, collectUsedDatasets as collectUsedScreenDatasets, componentLabel, componentsOf, findComponent, findPage, isScreenDirty, lowerComponent, moveComponent, movePage, nextComponentId, nextPageId as nextScreenPageId, normalizeCanvasConfig, normalizeComponent, normalizeComponents, normalizeComponentsByPage, normalizeComponentType, normalizePage, normalizePages, normalizeResolution, normalizeScreenDefinition, paletteGroups, raiseComponent, removeComponent, removePage, renamePage, resizeComponent, screenDefinitionsEqual, sendToBottom, serializeCanvasConfig, serializeScreen, serializeScreenDefinition, setDefaultPage, sortByZ, updateComponent, validateScreen, SCREEN_COMPONENT_TYPES, SCREEN_DEFAULT_COMPONENT_SIZE, SCREEN_DEFAULT_RESOLUTION, DEFAULT_CANVAS_BACKGROUND, SCREEN_DESIGN_PERM, SCREEN_DESIGNER_PLACEHOLDER_TEXT, SCREEN_MIN_COMPONENT_SIZE, SCREEN_PLAYER_PLACEHOLDER_TEXT, SCREEN_VIEW_PERM, } from './domain/screen-layout';
export { computeScale, isRotationDue, nextPageId, normalizePlayInterval, pageDuration, pageIds, prevPageId, SCREEN_DEFAULT_PLAY_INTERVAL, SCREEN_MIN_PLAY_INTERVAL, } from './domain/screen-play';
export { DEFAULT_DETAIL_COLUMNS, DEFAULT_DETAIL_PAGE_SIZE, EMPTY_TEXT, FIELD_WIDGETS, FIELD_WIDGET_MAP, FORM_RENDER_PERM, MASK_TEXT, RENDERER_EMPTY_HINT, RENDERER_FALLBACK_HINT, RENDERER_PLACEHOLDER_TEXT, RENDERER_UNKNOWN_TYPE_HINT, buildFieldPlan, buildRenderPlan, buildSubmitPayload, compileFieldRules, countPlanFields, displayFieldText, fallbackDetailColumns, isKnownFieldType, isSectionColumnsValid, isSubmitAllowed, maskFieldText, mkFieldRules, normalizeDetailRows, normalizeDetailSet, normalizeField, normalizeFieldOverrides, normalizeRenderMetadata, normalizeRenderMode, resolveBaselineEditable, resolveFieldRenderState, resolveFieldWidget, sectionSpan, validateDetailRows, validateDetails, validateFieldValue, validateFormData, visibleFields, } from './domain/form-render';
export { DEFAULT_LOCALE, EMPTY_I18N_FILTER, I18N_CACHE_FAILED_TEXT, I18N_CACHE_PLACEHOLDER_TEXT, I18N_DUPLICATE_KEY_TEXT, I18N_EMPTY_TEXT, I18N_ERRORS, I18N_EXPORT_PREFIX, I18N_MISSING_TEXT, I18N_NO_CHANGE_TEXT, I18N_PERM, I18N_PLACEHOLDER_TEXT, I18N_RELOAD_FAILED_TEXT, I18N_RELOAD_PLACEHOLDER_TEXT, I18N_SAVE_DONE_TEXT, I18N_SAVE_PLACEHOLDER_TEXT, I18N_SAVE_WARNING_TEXT, I18N_VALUE_TOO_LONG_TEXT, MESSAGE_FILTER_PAGE_SIZE, MESSAGE_PAGE_SIZE, MESSAGE_VALUE_MAX, MESSAGE_VIRTUAL_THRESHOLD, deriveMessageKey, deriveMissingLocales, diffMessages, filterMessages, isDirty, isMessageMissing, isModifiedRow, localeColumns, messageExportFileName, normalizeLocale, normalizeLocales, normalizeMessage, normalizeMessageKey, normalizeMessages, paginateMessages, resolveFilterParams, resolveMessageErrorText, shouldVirtualize, validateLocaleAdd, validateLocaleRemove, validateLocaleToggle, validateLocaleUpdate, validateMessageKey, validateMessageValue, } from './domain/i18n';
export { EMPTY_LOCALE_FILTER, I18N_DEFAULT_TAG_TEXT, I18N_DETAIL_EMPTY_TEXT, I18N_DETAIL_HINT, I18N_DETAIL_TITLE, I18N_FALLBACK_PREFIX, I18N_LOCALE_FAILED_TEXT, I18N_NAME_COUNT_PREFIX, I18N_NAME_MAX, I18N_NAME_MISSING_PREFIX, I18N_NAME_PLACEHOLDER, I18N_NAME_PLACEHOLDER_HINT, I18N_NAME_TOO_LONG_TEXT, I18N_REQUIRED_EMPTY_PREFIX, I18N_REQUIRED_TAG_TEXT, I18N_ROW_MISSING_TEXT, buildI18nPayload, buildLocaleRows, countFilled, deriveDefaultText, deriveMissingNameLocales, fallbackHintText, filterLocaleRows, isBlankName, isNamesEqual, isRowBlank, nameHintText, normalizeLocaleOptions, orderLocaleOptions, resolveDefaultLocale, resolveDisplayText, resolveRequiredLocale, validateI18nNames, } from './domain/i18n-name';
export { APPROVAL_ACTION_LABELS, APPROVAL_APPROVE_PERM, APPROVAL_COMMENT_FOLD, APPROVAL_COMMENT_MAX, APPROVAL_COMMENT_REQUIRED_TEXT, APPROVAL_COMMENT_TOO_LONG_TEXT, APPROVAL_DIAGRAM_FALLBACK_TEXT, APPROVAL_DUPLICATE_TEXT, APPROVAL_EMPTY_TEXT, APPROVAL_ERROR_HANDLERS, APPROVAL_NO_TASK_TEXT, APPROVAL_PLACEHOLDER_TEXT, APPROVAL_QUERY_PERM, APPROVAL_READONLY_TEXT, APPROVAL_TARGET_REQUIRED_TEXT, APPROVAL_UNGROUPED, countCodePoints, deriveApprovalKey, foldComment, groupRecordsByNode, normalizeAssignee, normalizeAssignees, normalizeInstance, normalizeNode, normalizeNodes, normalizeRecord, normalizeRecords, normalizeTask, resolveActiveNodeIndex, resolveApprovalActions, resolveApprovalErrorCode, resolveDiagramMode, resolveErrorHandling, resolveProgressSummary, resolveReadonlyInstance, resolveTimelineOrderRecords, resolveVisibleNodes, signProgress, validateAction, validateComment, validateTarget, } from './domain/approval';
export { deriveModelerKey, elementTypeOf, equivalentBpmnStructure, extractBpmnStructure, isSubsetElement, mergeValidateResults, MODELER_BLANK_XML, MODELER_DEFINE_PERM, MODELER_IMPORT_CONFIRM_TEXT, MODELER_PLACEHOLDER_TEXT, MODELER_PROPERTIES, MODELER_SUBSET, nextVersion, normalizeDefinition, propertiesFor, readElementProperties, resolveModelerErrorCode, resolveModelerErrorTarget, structureKey, validateBpmnStructure, validateProperties, } from './domain/process-modeler';
export { fnv1aHex, stableStringify } from './domain/serialize';
export { AUTO_WIDTH_SAMPLE_ROWS, DETAIL_PAGE_SIZE_DEFAULT, MAX_SORT_COLUMNS, PAGE_SIZE_DEFAULT, PAGE_SIZE_MAX, PAGE_SIZE_OPTIONS, TABLE_AUTO_WIDTH_PADDING, TABLE_BOOLEAN_FALSE_TEXT, TABLE_BOOLEAN_TRUE_TEXT, TABLE_CHAR_WIDTH, TABLE_DEFAULT_COLUMN_WIDTH, TABLE_MIN_COLUMN_WIDTH, TABLE_RENDER_PRIORITY, VIRTUAL_ROW_THRESHOLD, buildSortParams, clampColumnWidth, collectTreeKeys, columnSignature, flattenTreeRows, isVirtualEnabled, measureAutoWidth, mergeTableColumns, parseSortParams, resolveColumnStyle, resolveDensityToken, resolveRenderKind, resolveVisibleColumns, rowKeyOf, sortFieldOf, sortIndexOf, tableCellText, toggleSort, TREE_EXPAND_KEY_PREFIX, TREE_EXPAND_THRESHOLD_DEFAULT, buildTreeExpandKey, collectAncestorKeys, collectFirstLevelParentKeys, collectParentKeys, countTreeNodes, resolveDefaultExpandKeys, } from './domain/table';
export { FIELD_QUERY_OPERATORS, FILTER_DEFAULT_OPERATOR, FILTER_FIELD_TYPES, FILTER_INVALID_HINT_TEXT, FILTER_MULTI_SEPARATOR, FILTER_NOT_NULL_SUFFIX, FILTER_NULL_SUFFIX, FILTER_NUMBER_INVALID_TEXT, FILTER_OPERATORS, FILTER_OPERATOR_LABELS, FILTER_RANGE_END_SUFFIX, FILTER_RANGE_INVALID_TEXT, FILTER_RANGE_START_SUFFIX, FILTER_WIDGET_BY_TYPE, KEYWORD_FIELD, QUERY_COLLAPSE_THRESHOLD, QUERY_MAX_PER_ROW, QUERY_NARROW_BREAKPOINT, QUERY_SCHEME_SCOPES, QUERY_SCHEME_SCOPE_LABELS, QUERY_SCHEME_TARGETS, QUERY_SCHEME_TARGET_BUSINESS, SCHEME_DEFAULT_MAX, buildQueryParams, conditionText, defaultOperatorOf, fieldOf, filterActiveConditions, hasSchemeName, isConditionActive, normalizeConditions, normalizeSchemeEntry, normalizeSchemes, operatorsOf, pruneConditions, resolveDefaultScheme, resolveScheme, schemePriority, serializeCondition, serializeConditions, summarizeConditions, toConditionValue, validateConditionRange, } from './domain/filter';
export { STATUS_BULLET_SIZE, STATUS_BUILTIN_MAP, STATUS_FALLBACK_SEMANTIC, STATUS_FIXED_MAP, STATUS_SEMANTICS, STATUS_SEMANTIC_TOKENS, STATUS_SHAPES, describeStatus, isStatusSemantic, normalizeStatusColorMap, normalizeStatusValue, resolveStatusSemantic, resolveStatusText, statusTokenOf, } from './domain/status';
export { NOTIFICATION_BADGE_MAX, NOTIFICATION_BATCH_MAX, NOTIFICATION_PAGE_SIZE_DEFAULT, NOTIFICATION_PAGE_SIZE_MAX, NOTIFICATION_POLL_INTERVAL, NOTIFICATION_READ_FILTERS, NOTIFICATION_RECENT_LIMIT, NOTIFICATION_TYPES, applyIncoming, applyOptimisticRead, applyOptimisticReadAll, applyOptimisticRemove, badgeTextOf, buildNotificationParams, clampBadgeCount, connectionLabel, countUnread, filterNotificationMessages, hasJumpTarget, isPollingNeeded, isUnread, jumpTargetOf, mergeMessages, messageTypeLabel, normalizeNotificationMessage, normalizeNotificationMessages, normalizeNotificationPage, parseUnreadCount, recentMessages, resolveMessageSemantic, restoreSnapshot, shouldPoll, shouldShowBadge, } from './domain/notification';
export { ORG_CACHE_MAX, ORG_DEFAULT_PAGE_SIZE, ORG_DELETED_MARK, ORG_DISABLED_MARK, ORG_EMPTY_TEXT, ORG_EMPTY_VALUE, ORG_ERROR_TEXTS, ORG_JOIN, ORG_KEYWORD_MAX, ORG_LIMIT_DEFAULT, ORG_LOAD_ERROR_TEXT, ORG_PAGE_SIZE_MAX, ORG_PLACEHOLDER_TEXT, ORG_SEARCH_DEBOUNCE, ORG_STATUSES, ORG_TAG_COLLAPSE_DEFAULT, ORG_TARGETS, applyOrgSelection, buildOrgResolveQuery, buildOrgSearchQuery, clampOrgPage, clampOrgPageSize, findOrgDeptPath, findOrgItem, isBlankOrgKeyword, isOrgErrorCode, mergeOrgItems, normalizeOrgDeptTree, normalizeOrgIds, normalizeOrgItem, normalizeOrgItems, normalizeOrgKeyword, normalizeOrgKind, normalizeOrgNameRefs, normalizeOrgSearchQuery, normalizeOrgStatus, orgCacheKey, orgItemLabel, orgKindLabel, orgKindOfFieldType, orgLimitText, orgSelectionText, orgTagSummary, parseOrgDeptTree, parseOrgPage, removeOrgId, resolveOrgErrorText, toOrgTreeNodes, } from './domain/org';
export { DICT_ADV_FIXED_FIELDS, DICT_CACHE_MAX, DICT_CONDITION_MAX_DEPTH, DICT_DEFAULT_LOCALE, DICT_EMPTY_TEXT, DICT_EMPTY_VALUE, DICT_ERROR_TEXTS, DICT_JOIN, DICT_LARGE_THRESHOLD, DICT_LIMIT_TEXT_PREFIX, DICT_NO_MATCH_TEXT, DICT_OPERATORS, DICT_OPERATORS_BY_TYPE, DICT_OPERATOR_TEXTS, DICT_PLACEHOLDER_TEXT, DICT_PROBE_LIMIT, DICT_QUERY_PAGE_MAX, DICT_QUERY_PAGE_SIZE, DICT_SEARCH_DEBOUNCE, DICT_STATUSES, DICT_STORAGE_MAX_BYTES, DICT_STORAGE_PREFIX, DICT_SUBSET_MAX, DICT_SUPPORTED_LOCALES, applyDictSelection, buildDictAdvQuery, buildDictBatchQuery, buildDictTypeQuery, clampDictPage, clampDictPageSize, defaultOperatorsOf, dictAttrFieldOptions, dictCacheKey, dictFixedFieldOptions, dictLabelOf, dictSchemePriority, dictStorageKey, dictSubsetKey, dictTranslateValues, filterDictItems, findDictItem, isBlankDictKeyword, isDictErrorCode, isDictItemDisabled, isLargeDict, isOperatorAllowed, mergeDictItems, normalizeConditionGroup, normalizeDictBatchResult, normalizeDictItem, normalizeDictItems, normalizeDictKeyword, normalizeDictQueryScheme, normalizeDictTypeResult, normalizeDictValues, removeDictValue, resolveDictErrorText, toDictCascadeOptions, toDictTreeNodes, validateConditionGroup, } from './domain/dict';
export { FILE_COMPRESSED_MARK, FILE_DEBOUNCE, FILE_EMPTY_TEXT, FILE_EMPTY_VALUE, FILE_ERROR_TEXTS, FILE_INVALID_MARK, FILE_JOIN, FILE_LIMIT_DEFAULT, FILE_LIMIT_TEXT_PREFIX, FILE_LOCAL_ID_PREFIX, FILE_MAX_SIZE, FILE_PART_CONCURRENCY, FILE_PART_SIZE, FILE_PLACEHOLDER_TEXT, FILE_RETRY_BASE_MS, FILE_RETRY_MAX, FILE_RETRY_MAX_MS, FILE_TASK_CONCURRENCY, FILE_WHOLE_MAX_SIZE, IMAGE_ASPECT_TOLERANCE, IMAGE_COMPRESS_MAX_EDGE, IMAGE_COMPRESS_MIN_SIZE, IMAGE_COMPRESS_QUALITY, IMAGE_COMPRESS_SKIP_SIZE, IMAGE_CROP_ASPECT, IMAGE_CROP_OUTPUT_MAX_EDGE, UPLOAD_MODES, UPLOAD_TASK_PHASES, applyFileSelection, buildDedupQuery, buildMultipartInit, buildResolveQuery, checkFileMeta, checkImageDimension, createSha256, decideImageCompress, decideUploadMode, fileExtOf, fileListSummary, fileRefLabel, findFileRef, isFileErrorCode, isFileRefInvalid, isImageFile, isLocalFileRef, localFileRefId, matchAccept, mergeFileRefs, mergePartProgress, missingParts, moveFileRef, normalizeDedupRef, normalizeFileRef, normalizeFileRefs, normalizeFileValue, normalizePartResult, normalizeResolvedFiles, normalizeStoredFile, normalizeUploadSession, parseAcceptList, planParts, removeFileRef, resolveFileErrorText, retryDelayMs, shouldSkipCompress, } from './domain/file';
export { AUTH_ERROR_TEXTS, DEFAULT_AUTH_ERROR_TEXT, isAuthErrorCode, resolveAuthErrorText, } from './domain/auth-error';
export { CAPTCHA_EMPTY_VALUE, CAPTCHA_ERROR_TEXTS, CAPTCHA_DEFAULT_CHANNELS, CAPTCHA_FAIL_THRESHOLD, CAPTCHA_IMAGE_EMPTY_TEXT, CAPTCHA_IMAGE_MAX_LENGTH, CAPTCHA_IMAGE_MIN_LENGTH, CAPTCHA_INPUT_PLACEHOLDER, CAPTCHA_KINDS, CAPTCHA_LOAD_ERROR_TEXT, CAPTCHA_PASS_TEXT, CAPTCHA_PLACEHOLDER_TEXT, CAPTCHA_REFRESH_TEXT, CAPTCHA_REQUIRED_TEXT, CAPTCHA_RESEND_TEXT, CAPTCHA_SCENES, CAPTCHA_SEND_ERROR_TEXT, CAPTCHA_SEND_TEXT, CAPTCHA_SLIDER_HINT, CAPTCHA_SLIDER_RETRY_TEXT, CAPTCHA_SLIDER_TOLERANCE, CAPTCHA_SMS_COOLDOWN, CAPTCHA_SMS_INPUT_PLACEHOLDER, CAPTCHA_SMS_LENGTH, CAPTCHA_TRACE_MAX_POINTS, CAPTCHA_TRACE_MIN_POINTS, CAPTCHA_TTL, CAPTCHA_VERIFY_ERROR_TEXT, buildCaptchaChallengeQuery, buildCaptchaSmsQuery, buildCaptchaTrace, buildCaptchaVerifyQuery, captchaImageUrl, captchaInputHint, captchaKindText, checkCaptchaInput, clampCaptchaSeconds, countdownText, defaultCaptchaPolicy, isCaptchaErrorCode, maskCaptchaPhone, nextCountdown, normalizeCaptchaChallenge, normalizeCaptchaChannels, normalizeCaptchaKind, normalizeCaptchaPhone, normalizeCaptchaPolicy, normalizeCaptchaScene, normalizeCaptchaTrace, normalizeErrorCode, parseCaptchaSliderParams, resolveCaptchaErrorText, shouldRequireCaptcha, } from './domain/captcha';
export { isScannableIdpType, isSsoQrTerminal, nextSsoQrPollDelay, normalizeSsoQrAuthorizeInfo, normalizeSsoQrPollResult, resolveSsoQrStatusText, selectScannableProviders, SSO_QR_BACK_TEXT, SSO_QR_CONFIRMED_TEXT, SSO_QR_EMPTY_TEXT, SSO_QR_EXPIRED_TEXT, SSO_QR_FAILED_TEXT, SSO_QR_IDP_TYPES, SSO_QR_INIT_ERROR_REASON, SSO_QR_MAX_FAILURES, SSO_QR_PENDING_TEXT, SSO_QR_PHASES, SSO_QR_POLL_BASE, SSO_QR_POLL_ERROR_REASON, SSO_QR_POLL_MAX, SSO_QR_REFRESH_TEXT, SSO_QR_SCANNED_TEXT, SSO_QR_STATUSES, SSO_QR_SWITCH_TEXT, SSO_QR_TITLE_TEXT, } from './domain/sso-qr';
export { SEARCH_DEGRADE_FALLBACK_TEXT, SEARCH_DEGRADE_REASONS, SEARCH_DEGRADE_TEXT, SEARCH_DOC_TYPES, SEARCH_EMPTY_TEXT, SEARCH_FILE_PERM, SEARCH_FILE_UNSEARCHABLE_TEXT, SEARCH_KEYWORD_MAX, SEARCH_LOG_PERM, SEARCH_LOG_RANGE_EXCEED_TEXT, SEARCH_LOG_RANGE_MAX_DAYS, SEARCH_LOG_RANGE_REQUIRED_TEXT, SEARCH_PAGE_DEPTH_MAX, SEARCH_PAGE_SIZE_DEFAULT, SEARCH_PAGE_SIZE_MAX, SEARCH_PLACEHOLDER_TEXT, SEARCH_RATE_LIMIT_TEXT, SEARCH_RECENT_MAX, SEARCH_SUGGEST_DEBOUNCE, SEARCH_SUGGEST_LIMIT, SEARCH_SUGGEST_PER_DOMAIN, addRecentKeyword, buildFileParams, buildGlobalParams, buildLogParams, clampSearchPage, clampSearchPageSize, diffDays, domainLabelOf, filterAccessibleDomains, groupHits, hitKey, hitRouteTarget, isBlankKeyword, isSearchErrorCode, normalizeKeyword, normalizeRecentKeywords, normalizeSearchDomain, normalizeSearchDomains, normalizeSearchGroup, normalizeSearchHit, normalizeSearchHits, normalizeSearchResult, parseDegradeReason, parseDegraded, removeRecentKeyword, resolveSearchErrorText, topHits, validateLogRange, } from './domain/search';
export { AI_ACTION_STATES, AI_AUTO_EXECUTE_DISABLED_TEXT, AI_CHAT_PERM, AI_CITATION_TYPES, AI_CONFIRM_REQUIRED_TEXT, AI_MANAGE_PERM, AI_MESSAGE_MAX, AI_MESSAGE_STATUSES, AI_MODES, AI_PLACEHOLDER_TEXT, AI_PROMPT_MAX, AI_RESULT_KINDS, AI_REVOKE_UNAVAILABLE_TEXT, AI_ROLES, AI_SESSION_PAGE_SIZE_DEFAULT, AI_SESSION_PAGE_SIZE_MAX, AI_STREAM_PLACEHOLDER_TEXT, appendStreamChunk, applyActionConfirm, applyActionExecute, applyActionFail, applyActionRevoke, autoApproveAvailable, canAutoExecute, canRegenerate, canRevokeAction, canSend, canStop, citationTypeLabel, countAiCodePoints, deriveAiKey, deriveSessionTitle, failMessage, filterSessions, finishMessage, isAiErrorCode, messageStatusLabel, modeLabel, nextMessageId, nextSessionId, normalizeAiCitation, normalizeAiCitations, normalizeAiCitationType, normalizeAiMessage, normalizeAiMessages, normalizeAiMessageStatus, normalizeAiMode, normalizeAiResult, normalizeAiResultColumn, normalizeAiResultColumns, normalizeAiResultKind, normalizeAiRole, normalizeAiSession, normalizeAiSessions, normalizeAiSessionsPage, normalizePendingAction, reduceStream, requiresConfirm, resolveActionState, resolveAiErrorText, resolveAiSemantic, resolveRegenerateInput, sortSessions, splitContentSegments, startStreamMessage, stopMessage, validatePrompt, } from './domain/ai-chat';
export { METRIC_COMPACT_THRESHOLD, METRIC_COMPACT_UNITS, METRIC_COMPARE_KINDS, METRIC_COMPARE_LABELS, METRIC_EMPTY_TEXT, METRIC_FORMATS, METRIC_PRECISION_MAX, METRIC_TREND_DIRECTIONS, METRIC_TREND_PRECISION, SPARKLINE_DEFAULT_HEIGHT, SPARKLINE_DEFAULT_WIDTH, SPARKLINE_PADDING, buildSparkline, clampMetricRatio, compactMetricValue, formatMetricValue, interpolateMetricValue, isMetricEmpty, normalizeTrend, resolveMetricTrend, } from './domain/metric';
export { LIST_DENSITIES, LIST_PREF_KEY_PREFIX, LIST_PREF_MAX_BYTES, LIST_PREF_MAX_CONDITIONS, buildListPrefKey, emptyListPreference, fromColumnPreferences, isListPreferenceOversized, listPreferenceBytes, normalizeListPreference, pruneListPreference, toColumnPreferences, trimListPreference, withQuery, withoutQuery, } from './domain/list-preference';
