/**
 * `@bms/core`：前端框架无关核心运行时入口。
 *
 * 纯 TS，不依赖 Vue / UI 库 / 插件 / 宿主（护栏 `tests/guard-core-framework-agnostic.spec.ts`）。
 * 基类与能力导出随 `02_01` ~ `02_06` 就位后在本入口追加。
 */

export {
  BaseObject,
  configureBase,
  getBaseSinks,
  resetBaseSinks,
  type BaseConfigSource,
  type BaseLoggerSink,
  type BaseReporterSink,
  type BaseSinks,
  type LogLevel,
} from './base/BaseObject'
export { withBaseObject, type BaseObjectSurface } from './base/mixin'
export {
  BaseComponent,
  type ComponentProps,
  type DensityToken,
  type LifecycleEvent,
  type LifecycleListener,
  type LifecyclePayload,
  type SizeToken,
} from './base/BaseComponent'

export { ErrorCodes, FRONTEND_RESERVED_SEGMENT, isFrontendReservedCode, type ErrorCode } from './mechanisms/error-codes'
export { BaseCapability } from './mechanisms/capability'
export { BasePluggable, DEFAULT_CONTRACT_VERSION } from './mechanisms/pluggable'
export { BaseError, type BaseErrorOptions } from './mechanisms/error'
export { BaseProviderRegistry, CapabilityRegistry } from './mechanisms/registry'
export { BaseProvider } from './mechanisms/provider'
export { BaseFactory } from './mechanisms/factory'
export { BaseAsyncResource, type Disposable } from './mechanisms/resource'
export { BaseSubscription } from './mechanisms/subscription'
export { BaseNullObject, BasePlaceholder, BaseStub, type PlaceholderReason } from './mechanisms/placeholder'

export { BaseValue, type ValueListener } from './capabilities/value'
export { BaseField, type FieldTrigger } from './capabilities/field'
export { BaseSized } from './capabilities/sized'
export { BaseDataState, type DataStateListener, type DataStateName, type SettleState } from './capabilities/data-state'
export {
  BaseChart,
  type ChartEngineAdapter,
  type ChartJobs,
  type ChartLoadInput,
} from './capabilities/chart'
export {
  BaseReportDesigner,
  type ReportBlockAction,
  type ReportJobs,
  type ReportPhase,
  type ReportPreviewResult,
  type ReportSaveResult,
  type ReportSnapshot,
} from './capabilities/report-designer'
export {
  BaseScreenDesigner,
  type ScreenBlockAction,
  type ScreenDesignerJobs,
  type ScreenDesignerPhase,
  type ScreenPreviewResult,
  type ScreenSaveResult,
  type ScreenSnapshot,
} from './capabilities/screen-designer'
export {
  BaseScreenPlayer,
  type ScreenPlaySnapshot,
  type ScreenPlayerJobs,
  type ScreenPlayerPhase,
} from './capabilities/screen-player'
export { BaseOverlay, type OverlayListener } from './capabilities/overlay'
export { BaseNotice, type NoticeItem, type NoticeType } from './capabilities/notice'
export { BaseLabeled, type LabelPosition } from './capabilities/labeled'
export { BaseValidatable, type Validator } from './capabilities/validatable'
export {
  assertCapabilityGraph,
  CAPABILITY_MANIFEST,
  validateCapabilityGraph,
  type CapabilityProblem,
  type CapabilityProblemKind,
} from './capabilities/manifest'

export { BasePersistedState, type PersistedRemoteSaver, type PersistedStorage } from './capabilities/persisted-state'
export {
  BaseWizard,
  type WizardResult,
  type WizardStep,
  type WizardValidation,
  type WizardValidatorResult,
} from './capabilities/wizard'
export { BaseSelection, type SelectionKey, type SelectionMode, type SelectionSummary } from './capabilities/selection'
export {
  BaseBulkAction,
  type BulkActionContext,
  type BulkActionDef,
  type BulkActionPhase,
  type BulkActionProgress,
  type BulkActionResult,
} from './capabilities/bulk-action'
export { BaseTheme, type BrandConfig, type ResolvedTheme, type ThemeMode } from './capabilities/theme'
export { BaseTenant, type TenantSummary, type TenantSwitchPhase, type TenantSwitchSteps } from './capabilities/tenant'
export { BasePrintTemplate, type PrintBrand, type PrintContext } from './capabilities/print-template'
export {
  BasePrint,
  PRINT_JOB_PLACEHOLDER,
  type PrintBatchMode,
  type PrintJobHandler,
  type PrintJobPayload,
  type PrintJobResult,
  type PrintJobs,
  type PrintPhase,
  type PrintProgress,
} from './capabilities/print'
export {
  BasePermissionConfig,
  type PermissionCodesHandler,
  type PermissionJobs,
  type PermissionLoadHandler,
  type PermissionPhase,
  type PermissionSubmitHandler,
  type PermissionSubmitResult,
} from './capabilities/permission-config'
export { BaseMounted, type MountListener } from './capabilities/mounted'
export { BaseDesignToken, type DesignTokens, type ThemeListener } from './capabilities/design-token'
export { BaseClickable } from './capabilities/interactive'
export { BaseDragDrop, type DragListener, type DragPayload, type DragPhase } from './capabilities/drag-drop'
export { BaseTabs, type TabItem } from './capabilities/tabs'
export { BaseLocale, type LocaleFormatContext } from './capabilities/locale'
export { BaseAccess } from './capabilities/access'
export { BaseModuleContext, type ModuleContext, type ModuleContextKey } from './capabilities/module-context'

export {
  BaseAsyncTask,
  type TaskExecutor,
  type TaskPollOutcome,
  type TaskPoller,
  type TaskProgress,
  type TaskStatus,
  type TaskSubmitter,
} from './capabilities/async-task'
export { BaseUploadEngine, type UploadProgressReporter, type Uploader } from './capabilities/upload-engine'
export {
  BaseFileDownload,
  DOWNLOAD_PLACEHOLDER_TEXT,
  type DownloadFetcher,
  type DownloadPhase,
  type DownloadRequest,
  type DownloadResult,
  type DownloadSource,
  type DownloadTrigger,
} from './capabilities/file-download'
export {
  BaseImportFlow,
  type ImportAbortSignal,
  type ImportDownloadHandler,
  type ImportDownloadInput,
  type ImportExecuteHandler,
  type ImportJobs,
  type ImportPhase,
  type ImportStep,
} from './capabilities/import-flow'
export {
  BaseExportFlow,
  type ExportHandler,
  type ExportJobs,
  type ExportPhase,
  type ExportPollHandler,
  type ExportRequest,
  type ExportResult,
} from './capabilities/export-flow'
export {
  BaseFormDesigner,
  type DesignerBlockAction,
  type DesignerDropInput,
  type DesignerExtFieldResult,
  type DesignerJobs,
  type DesignerPhase,
  type DesignerSaveResult,
  type DesignerSnapshot,
} from './capabilities/form-designer'
export {
  BaseFormRenderer,
  type FormRendererJobs,
  type RecordSnapshot,
  type RendererPhase,
  type SubmitResult,
} from './capabilities/form-renderer'
export {
  BaseMessageCatalog,
  type LocaleChangeInput,
  type LocaleChangeKind,
  type MessageJobs,
  type MessageLoadInput,
  type MessagePhase,
  type MessageSaveInput,
  type SaveResult,
} from './capabilities/message-catalog'
export {
  BaseApprovalFlow,
  type ApprovalJobs,
  type ApprovalLoadDiagramHandler,
  type ApprovalLoadInstanceHandler,
  type ApprovalLoadRecordsHandler,
  type ApprovalSubmitHandler,
  type ApprovalSubmitInput,
} from './capabilities/approval-flow'
export {
  BaseProcessModeler,
  type ModelerDeployHandler,
  type ModelerJobs,
  type ModelerLoadHandler,
  type ModelerSaveHandler,
  type ModelerSubmitKind,
  type ModelerValidateHandler,
} from './capabilities/process-modeler'
export { BaseEditorKernel, type EditorMode } from './capabilities/editor-kernel'
export { BaseOptionSource, type OptionItem } from './capabilities/option-source'
export { BasePresignedUrl, type PresignedResult } from './capabilities/presigned-url'
export { BaseWatermark } from './capabilities/watermark'
export { BaseUserDisplay, type UserDisplayInfo, type UserStatus } from './capabilities/user-display'
export { BaseDynamicRoutes, type RouteNode } from './capabilities/dynamic-routes'
export { BaseFormMeta } from './capabilities/form-meta'
export { BaseFormPage, type FormMode } from './capabilities/form-page'

export { BaseInput } from './capabilities/input'
export { BaseDisplay } from './capabilities/display'
export { BaseTable, type SortSpec } from './capabilities/table'
export { BaseList } from './capabilities/list'
export { BaseTreeData, type TreeNode } from './capabilities/tree-data'
export { BaseModalShell } from './capabilities/modal-shell'
export { BaseFormContainer } from './capabilities/form-container'
export { BaseContainer } from './capabilities/container'
export { BaseLayout } from './capabilities/layout'
export { BaseMediaContent, type MediaState } from './capabilities/media'
export { BaseFeedback, type FeedbackState } from './capabilities/feedback'
export {
  BaseNotificationCenter,
  type NotificationJobs,
  type NotificationPhase,
  type NotificationRealtimeAdapter,
} from './capabilities/notification-center'
export { BaseNotification, type NotificationItem } from './capabilities/notification'
export { BaseColumnConfig, type ColumnSeed, type ColumnState } from './capabilities/column-config'
export { BaseQueryScheme, type QueryCondition, type QueryScheme } from './capabilities/query-scheme'
export { BaseFieldShell } from './capabilities/field-shell'
export { BaseFieldPerm, type FieldPermission } from './capabilities/field-perm'

export {
  EMPTY_PLACEHOLDER,
  formatAmount,
  formatDate,
  formatDateTime,
  formatDuration,
  formatFileSize,
  formatNumber,
  formatPercent,
  formatCompactTimestamp,
  formatRelativeTime,
  mask,
  type FormatContext,
} from './domain/format'
export { amount, codePattern, email, lengthRange, numberRange, phone, required, url } from './domain/validators'
export { evaluatePermission, type PermissionMode } from './domain/permission'
export {
  PERMISSION_ERROR_TARGETS,
  PERMISSION_GRANT_CODE,
  PERMISSION_PLACEHOLDER_TEXT,
  PERMISSION_SUBJECT_LIMIT,
  PERMISSION_TABS,
  applyPermissionCheck,
  bindSubject,
  collectDataScopes,
  collectFieldEntries,
  collectPayload,
  deriveGranted,
  deriveIdempotencyKey,
  findFieldMismatch,
  findFieldPerm,
  findPermissionNode,
  flattenPermissionTree,
  isGrantable,
  normalizeDataScopes,
  normalizeFieldPerms,
  payloadKey,
  resolveCheckState,
  resolveErrorCode,
  resolveErrorTarget,
  setDataScope,
  setFieldPerm,
  unbindSubject,
  type DataScopeEntry,
  type DataScopeInputRow,
  type DataScopeRow,
  type FieldPermCell,
  type FieldPermEntry,
  type FieldPermInputCell,
  type FieldPermInputRow,
  type FieldPermRow,
  type FlatPermissionNode,
  type PermissionCheckState,
  type PermissionErrorTarget,
  type PermissionGranted,
  type PermissionNode,
  type PermissionNodeType,
  type PermissionPayload,
  type PermissionSnapshot,
  type PermissionSubject,
  type PermissionSubjectType,
  type PermissionTab,
  type SubjectBindResult,
} from './domain/permission-config'
export { resolveToken } from './domain/token'
export {
  DEFAULT_BRAND_PRIMARY,
  darken,
  deriveBrandTokens,
  isValidColor,
  lighten,
  luminance,
  mixColor,
  normalizeBrand,
  parseColor,
  resolveThemeMode,
  toHex,
  type BrandTokenMap,
  type RgbColor,
  type ThemeResolveInput,
} from './domain/brand'
export {
  MAX_DECIMAL_PRECISION,
  compareDecimal,
  fromMinorUnits,
  isDecimal,
  isDecimalInRange,
  normalizeDecimal,
  sanitizePrecision,
  toMinorUnits,
  type DecimalRangeOptions,
} from './domain/decimal'
export { computeVirtualRange, type VirtualRange, type VirtualRangeOptions } from './domain/virtual-range'
export {
  PLACEHOLDER_MENU,
  filterMenuByKeyword,
  filterMenuByPermission,
  findMenuByPath,
  flattenMenu,
  toRouteNodes,
  type MenuNode,
} from './domain/menu'
export {
  PREFERENCE_DEFAULTS,
  PREFERENCE_KEYS,
  applyPreferenceDefaults,
  diffPreferences,
  isPreferenceEnabled,
  isPreferenceVisible,
  mergePreferences,
  readPreferenceValue,
  resolvePreferenceDefaults,
  sanitizePreferences,
  writePreferenceValue,
  type PreferenceKey,
  type PreferencePolicy,
  type PreferencePolicyMap,
  type PreferenceValues,
} from './domain/preference'

export {
  PAPER_SIZES,
  PRINT_MISSING_TEXT,
  PRINT_STYLE_VARS,
  buildPrintPages,
  computeRowsPerPage,
  distributeFields,
  formatCellValue,
  formatPageFooter,
  paginateRows,
  resolvePaperSize,
  resolvePrintTone,
  resolveRowsPerPage,
  sumNumeric,
  type BuildPagesInput,
  type PageFooterInput,
  type PaperName,
  type PaperOrientation,
  type PaperSize,
  type PrintCellFormat,
  type PrintColumnDef,
  type PrintData,
  type PrintFieldDef,
  type PrintPage,
  type PrintRowData,
  type PrintStyleVar,
  type PrintTemplateDef,
  type PrintTone,
  type PrintToneResolve,
  type RowCapacityInput,
} from './domain/print'
export {
  IMPORT_ACCEPT,
  IMPORT_DEFAULT_MAX_SIZE,
  IMPORT_ERROR_DISPLAY_LIMIT,
  IMPORT_ERROR_PAGE_SIZE,
  IMPORT_FILE_ERROR_RANGE,
  IMPORT_PERM,
  IMPORT_PLACEHOLDER_TEXT,
  checkImportFile,
  deriveImportKey,
  errorReportFileName,
  fileExtension,
  isFileLevelError,
  normalizeAccept,
  normalizeImportResult,
  paginateImportErrors,
  resolveImportErrorText,
  resolveImportSummary,
  templateFileName,
  type ImportErrorPage,
  type ImportErrorRow,
  type ImportErrorText,
  type ImportFailReason,
  type ImportFileCheck,
  type ImportFileMeta,
  type ImportResult,
  type ImportResultInput,
  type ImportSummaryState,
} from './domain/import'
export {
  EXPORT_EMPTY_TEXT,
  EXPORT_FILE_EXT,
  EXPORT_PERM,
  EXPORT_PLACEHOLDER_TEXT,
  EXPORT_PLAIN_PERM,
  EXPORT_QUEUED_TEXT,
  canExportPlain,
  exportErrorMessage,
  exportFileName,
  normalizeExportParams,
  normalizeSelectedIds,
  resolveExportDecision,
  resolveExportMode,
  type ExportDecision,
  type ExportDecisionInput,
  type ExportMode,
  type ExportQueryParams,
  type ExportScope,
} from './domain/export'

export {
  type LoadedModule,
  type ModuleDefinition,
  type ModuleHostContext,
  type ModuleLoader,
  type ModuleManifest,
  type ModuleRegistration,
  type ModuleRouteDeclaration,
} from './module/types'
export { MODULE_NAME_PATTERN, defineModule } from './module/define'

export {
  ComponentProvider,
  ComponentRegistry,
  FieldRendererProvider,
  FieldRendererRegistry,
  IconProvider,
  IconRegistry,
  ICON_KEY_PATTERN,
  REGISTRY_KEY_PATTERN,
  RouteMenuProvider,
  RouteMenuRegistry,
  WorkbenchCardProvider,
  WorkbenchCardRegistry,
  assertIconKey,
  assertNamespacedKey,
  createRegistries,
  schemaError,
  type FrontendRegistries,
  type IconProviderOptions,
} from './registries'
export { LocalModuleLoader } from './module/loader'

export { BaseApi, type HttpMethod } from './contracts/api'
export {
  configureRequestAdapter,
  getRequestAdapter,
  request,
  type ApiResponse,
  type PageResponse,
  type RequestAdapter,
  type RequestConfig,
} from './contracts/request'
export { BaseDataObject } from './contracts/data-object'
export { BaseEntity } from './contracts/entity'
export { BasePageQuery, type SortOrder } from './contracts/page-query'
export {
  DEFAULT_LABEL_WIDTH,
  DEFAULT_LAYOUT_COLUMNS,
  DEFAULT_SECTION_KEY,
  DESIGNER_EMPTY_HINT,
  DESIGNER_PLACEHOLDER_TEXT,
  DETAIL_WIDTH_RANGE,
  EXT_COLUMN_PREFIX,
  EXT_FIELD_TYPES,
  EXT_OPTION_TYPES,
  FORMDESIGN_PERM,
  FORMDESIGN_VIEW_PERM,
  LABEL_WIDTH_RANGE,
  SECTION_COLUMNS,
  SECTION_FIELD_HINT,
  SECTION_KEY_PREFIX,
  addSection,
  canDragField,
  checkExtField,
  collectFieldKeys,
  countLayoutFields,
  defaultLayout,
  emptyLayout,
  extColumnName,
  extFieldNeedsOptions,
  findDisabledFields,
  findDuplicateFields,
  findSection,
  findUnknownFields,
  hasField,
  insertField,
  isLayoutDirty,
  isLayoutEmpty,
  layoutEqual,
  locateField,
  moveField,
  newSectionKey,
  normalizeColumns,
  normalizeFieldRef,
  normalizeFieldRefs,
  normalizeLayout,
  normalizeSelection,
  removeField,
  removeSection,
  renameSection,
  resolveEffectiveLayout,
  resolveExtDdlStatus,
  resolveLayoutForLevel,
  resolveLevelReadOnly,
  resolveRestoreTarget,
  setDetailColumns,
  setLabelPosition,
  setLabelWidth,
  setQueryFields,
  setSectionColumns,
  toRenderMetadata,
  toggleColSpan,
  validateLayout,
  type DesignerLevel,
  type DesignerSelection,
  type ExtDdlStatus,
  type ExtFieldCheck,
  type ExtFieldDraft,
  type ExtFieldOption,
  type FieldGroup,
  type FieldRenderAttrs,
  type FieldRule,
  type FieldStatus,
  type FormField,
  type FormLayout,
  type FormLayoutInput,
  type FormLayoutLevels,
  type LayoutDetailColumnInput,
  type LayoutFieldRefInput,
  type LayoutGroupInput,
  type LayoutLabelPosition,
  type LayoutSectionInput,
  type LayoutDictAdvanced,
  type LayoutDetail,
  type LayoutDetailColumn,
  type LayoutEffective,
  type LayoutFieldRef,
  type LayoutGroup,
  type LayoutIssueKind,
  type LayoutMain,
  type LayoutQuery,
  type LayoutRestoreTarget,
  type LayoutSection,
  type LayoutValidationIssue,
  type LayoutValidationResult,
  type SectionColumns,
} from './domain/form-layout'
export {
  buildChartOption,
  buildChartTheme,
  chartConfigEqual,
  chartKindOption,
  chartOptionSignature,
  CHART_AXIS_TOKEN,
  CHART_CACHE_TTL,
  CHART_COLOR_FALLBACK,
  CHART_COLOR_TOKENS,
  CHART_CONFIG_VERSION,
  CHART_EMPTY_TEXT,
  CHART_GRID_TOKEN,
  CHART_KINDS,
  CHART_PLACEHOLDER_TEXT,
  CHART_RESIZE_INTERVAL,
  CHART_TEXT_TOKEN,
  CHART_TOOLTIP_BG_TOKEN,
  CHART_TOOLTIP_TEXT_TOKEN,
  CHART_VIEW_PERM,
  deepMerge,
  defaultMapping,
  emptyMapping,
  hasChartAxis,
  isChartEmpty,
  isMappingEmpty,
  isNumericField,
  mergeChartOption,
  normalizeChartConfig,
  normalizeChartKind,
  normalizeMapping,
  resolveChartMode,
  rotatePalette,
  serializeChartConfig,
  shouldReplaceOption,
  shouldResize,
  toNumber,
  type ChartConfig,
  type ChartDatasetResult,
  type ChartField,
  type ChartKind,
  type ChartKindOption,
  type ChartMapping,
  type ChartRenderMode,
  type ChartStateName,
  type ChartStyleOptions,
  type ChartTheme,
  type ChartThemeMode,
  type ChartTokenReader,
  type ChartView,
} from './domain/chart'
export {
  addChartItem,
  buildItemConfig,
  centerChartItem,
  collectUsedDatasets,
  countCharts,
  datasetOptions,
  duplicateChartItem,
  fieldsOf,
  findChartItem,
  hasOverlap,
  isReportDirty,
  moveChartItem,
  nextChartId,
  normalizeCell,
  normalizeChartItem,
  normalizeReportCharts,
  removeChartItem,
  reportChartsEqual,
  resizeChartItem,
  resolveChartTitle,
  serializeChartConfigs,
  serializeReport,
  serializeReportLayout,
  updateChartItem,
  validateReport,
  REPORT_DEFAULT_CELL,
  REPORT_DESIGN_PERM,
  REPORT_DESIGNER_PLACEHOLDER_TEXT,
  REPORT_GRID_COLUMNS,
  REPORT_MAX_CELL,
  REPORT_MIN_CELL,
  REPORT_VIEW_PERM,
  type ReportChartItem,
  type ReportDataset,
  type ReportDatasetParam,
  type ReportDefinition,
  type ReportField,
  type ReportIssueKind,
  type ReportValidationIssue,
  type ReportValidationResult,
} from './domain/report-layout'
export {
  addComponent,
  addPage,
  bringToTop,
  canvasStyle,
  collectUsedDatasets as collectUsedScreenDatasets,
  componentLabel,
  componentsOf,
  findComponent,
  findPage,
  isScreenDirty,
  lowerComponent,
  moveComponent,
  movePage,
  nextComponentId,
  nextPageId as nextScreenPageId,
  normalizeCanvasConfig,
  normalizeComponent,
  normalizeComponents,
  normalizeComponentsByPage,
  normalizeComponentType,
  normalizePage,
  normalizePages,
  normalizeResolution,
  normalizeScreenDefinition,
  paletteGroups,
  raiseComponent,
  removeComponent,
  removePage,
  renamePage,
  resizeComponent,
  screenDefinitionsEqual,
  sendToBottom,
  serializeCanvasConfig,
  serializeScreen,
  serializeScreenDefinition,
  setDefaultPage,
  sortByZ,
  updateComponent,
  validateScreen,
  SCREEN_COMPONENT_TYPES,
  SCREEN_DEFAULT_COMPONENT_SIZE,
  SCREEN_DEFAULT_RESOLUTION,
  SCREEN_DESIGN_PERM,
  SCREEN_DESIGNER_PLACEHOLDER_TEXT,
  SCREEN_MIN_COMPONENT_SIZE,
  SCREEN_PLAYER_PLACEHOLDER_TEXT,
  SCREEN_VIEW_PERM,
  type ScreenCanvasConfig,
  type ScreenComponent,
  type ScreenComponentType,
  type ScreenDefinition,
  type ScreenIssueKind,
  type ScreenPage,
  type ScreenValidationIssue,
  type ScreenValidationResult,
} from './domain/screen-layout'
export {
  computeScale,
  isRotationDue,
  nextPageId,
  normalizePlayInterval,
  pageDuration,
  pageIds,
  prevPageId,
  SCREEN_DEFAULT_PLAY_INTERVAL,
  SCREEN_MIN_PLAY_INTERVAL,
  type ScreenScaleMode,
  type ScreenScaleTransform,
} from './domain/screen-play'
export {
  DEFAULT_DETAIL_COLUMNS,
  DEFAULT_DETAIL_PAGE_SIZE,
  EMPTY_TEXT,
  FIELD_WIDGETS,
  FIELD_WIDGET_MAP,
  FORM_RENDER_PERM,
  MASK_TEXT,
  RENDERER_EMPTY_HINT,
  RENDERER_FALLBACK_HINT,
  RENDERER_PLACEHOLDER_TEXT,
  RENDERER_UNKNOWN_TYPE_HINT,
  buildFieldPlan,
  buildRenderPlan,
  buildSubmitPayload,
  compileFieldRules,
  countPlanFields,
  displayFieldText,
  fallbackDetailColumns,
  isKnownFieldType,
  isSectionColumnsValid,
  isSubmitAllowed,
  maskFieldText,
  mkFieldRules,
  normalizeDetailRows,
  normalizeDetailSet,
  normalizeField,
  normalizeFieldOverrides,
  normalizeRenderMetadata,
  normalizeRenderMode,
  resolveBaselineEditable,
  resolveFieldRenderState,
  resolveFieldWidget,
  sectionSpan,
  validateDetailRows,
  validateDetails,
  validateFieldValue,
  validateFormData,
  visibleFields,
  type DetailDataSet,
  type DetailRenderError,
  type DetailValidationResult,
  type FieldRenderOverride,
  type FieldRenderState,
  type FormFieldInput,
  type FormRenderError,
  type FormRenderMode,
  type FormValidationResult,
  type FormWidget,
  type RenderDetailColumn,
  type RenderFieldPlan,
  type RenderGroupPlan,
  type RenderMetadataInput,
  type RenderPlan,
  type RenderSectionPlan,
  type SubmitPayload,
} from './domain/form-render'
export {
  DEFAULT_LOCALE,
  EMPTY_I18N_FILTER,
  I18N_CACHE_FAILED_TEXT,
  I18N_CACHE_PLACEHOLDER_TEXT,
  I18N_DUPLICATE_KEY_TEXT,
  I18N_EMPTY_TEXT,
  I18N_ERRORS,
  I18N_EXPORT_PREFIX,
  I18N_MISSING_TEXT,
  I18N_NO_CHANGE_TEXT,
  I18N_PERM,
  I18N_PLACEHOLDER_TEXT,
  I18N_RELOAD_FAILED_TEXT,
  I18N_RELOAD_PLACEHOLDER_TEXT,
  I18N_SAVE_DONE_TEXT,
  I18N_SAVE_PLACEHOLDER_TEXT,
  I18N_SAVE_WARNING_TEXT,
  I18N_VALUE_TOO_LONG_TEXT,
  MESSAGE_FILTER_PAGE_SIZE,
  MESSAGE_PAGE_SIZE,
  MESSAGE_VALUE_MAX,
  MESSAGE_VIRTUAL_THRESHOLD,
  deriveMessageKey,
  deriveMissingLocales,
  diffMessages,
  filterMessages,
  isDirty,
  isMessageMissing,
  isModifiedRow,
  localeColumns,
  messageExportFileName,
  normalizeLocale,
  normalizeLocales,
  normalizeMessage,
  normalizeMessageKey,
  normalizeMessages,
  paginateMessages,
  resolveFilterParams,
  resolveMessageErrorText,
  shouldVirtualize,
  validateLocaleAdd,
  validateLocaleRemove,
  validateLocaleToggle,
  validateLocaleUpdate,
  validateMessageKey,
  validateMessageValue,
  type I18nChangeSet,
  type I18nCheckResult,
  type I18nFilter,
  type I18nLocaleInput,
  type I18nLocaleItem,
  type I18nLocaleStatus,
  type I18nMessageInput,
  type I18nMessageItem,
  type MessagePage,
} from './domain/i18n'
export {
  APPROVAL_ACTION_LABELS,
  APPROVAL_APPROVE_PERM,
  APPROVAL_COMMENT_FOLD,
  APPROVAL_COMMENT_MAX,
  APPROVAL_COMMENT_REQUIRED_TEXT,
  APPROVAL_COMMENT_TOO_LONG_TEXT,
  APPROVAL_DIAGRAM_FALLBACK_TEXT,
  APPROVAL_DUPLICATE_TEXT,
  APPROVAL_EMPTY_TEXT,
  APPROVAL_ERROR_HANDLERS,
  APPROVAL_NO_TASK_TEXT,
  APPROVAL_PLACEHOLDER_TEXT,
  APPROVAL_QUERY_PERM,
  APPROVAL_READONLY_TEXT,
  APPROVAL_TARGET_REQUIRED_TEXT,
  APPROVAL_UNGROUPED,
  countCodePoints,
  deriveApprovalKey,
  foldComment,
  groupRecordsByNode,
  normalizeAssignee,
  normalizeAssignees,
  normalizeInstance,
  normalizeNode,
  normalizeNodes,
  normalizeRecord,
  normalizeRecords,
  normalizeTask,
  resolveActiveNodeIndex,
  resolveApprovalActions,
  resolveApprovalErrorCode,
  resolveDiagramMode,
  resolveErrorHandling,
  resolveProgressSummary,
  resolveReadonlyInstance,
  resolveTimelineOrderRecords,
  resolveVisibleNodes,
  signProgress,
  validateAction,
  validateComment,
  validateTarget,
  type ApprovalAction,
  type ApprovalAssignee,
  type ApprovalAttachment,
  type ApprovalCheckResult,
  type ApprovalDiagramMode,
  type ApprovalErrorHandling,
  type ApprovalErrorHandlingItem,
  type ApprovalInstance,
  type ApprovalInstanceInput,
  type ApprovalInstanceStatus,
  type ApprovalNode,
  type ApprovalNodeInput,
  type ApprovalNodeStatus,
  type ApprovalPartState,
  type ApprovalPhase,
  type ApprovalProgressSummary,
  type ApprovalRecord,
  type ApprovalRecordGroup,
  type ApprovalRecordInput,
  type ApprovalSignProgress,
  type ApprovalSubmitPayload,
  type ApprovalSubmitResult,
  type ApprovalTask,
  type ApprovalTaskInput,
  type ApprovalTimelineOrder,
} from './domain/approval'
export {
  deriveModelerKey,
  elementTypeOf,
  equivalentBpmnStructure,
  extractBpmnStructure,
  isSubsetElement,
  mergeValidateResults,
  MODELER_BLANK_XML,
  MODELER_DEFINE_PERM,
  MODELER_IMPORT_CONFIRM_TEXT,
  MODELER_PLACEHOLDER_TEXT,
  MODELER_PROPERTIES,
  MODELER_SUBSET,
  nextVersion,
  normalizeDefinition,
  propertiesFor,
  readElementProperties,
  resolveModelerErrorCode,
  resolveModelerErrorTarget,
  structureKey,
  validateBpmnStructure,
  validateProperties,
  type BpmnStructure,
  type ModelerAssigneeSource,
  type ModelerDefinition,
  type ModelerDefinitionInput,
  type ModelerDefinitionStatus,
  type ModelerElement,
  type ModelerElementProperties,
  type ModelerElementType,
  type ModelerErrorTarget,
  type ModelerFlow,
  type ModelerMultiRule,
  type ModelerPhase,
  type ModelerPropertyItem,
  type ModelerPropertyKind,
  type ModelerSubmitResult,
  type ModelerValidateError,
  type ModelerValidateResult,
  type ModelerValidateSource,
} from './domain/process-modeler'
export { fnv1aHex, stableStringify } from './domain/serialize'
export {
  AUTO_WIDTH_SAMPLE_ROWS,
  DETAIL_PAGE_SIZE_DEFAULT,
  MAX_SORT_COLUMNS,
  PAGE_SIZE_DEFAULT,
  PAGE_SIZE_MAX,
  PAGE_SIZE_OPTIONS,
  TABLE_AUTO_WIDTH_PADDING,
  TABLE_BOOLEAN_FALSE_TEXT,
  TABLE_BOOLEAN_TRUE_TEXT,
  TABLE_CHAR_WIDTH,
  TABLE_DEFAULT_COLUMN_WIDTH,
  TABLE_MIN_COLUMN_WIDTH,
  TABLE_RENDER_PRIORITY,
  VIRTUAL_ROW_THRESHOLD,
  buildSortParams,
  clampColumnWidth,
  collectTreeKeys,
  columnSignature,
  flattenTreeRows,
  isVirtualEnabled,
  measureAutoWidth,
  mergeTableColumns,
  parseSortParams,
  resolveColumnStyle,
  resolveDensityToken,
  resolveRenderKind,
  resolveVisibleColumns,
  rowKeyOf,
  sortFieldOf,
  sortIndexOf,
  tableCellText,
  toggleSort,
  type TableColumn,
  type TableColumnAlign,
  type TableColumnFixed,
  type TableColumnFormat,
  type TableColumnMeta,
  type TableColumnState,
  type TableDensity,
  type TableRenderKind,
  type TableSortParams,
  type TableSortSpec,
  type TableTreeOptions,
  type TableTreeRow,
} from './domain/table'
export {
  FIELD_QUERY_OPERATORS,
  FILTER_DEFAULT_OPERATOR,
  FILTER_FIELD_TYPES,
  FILTER_INVALID_HINT_TEXT,
  FILTER_MULTI_SEPARATOR,
  FILTER_NOT_NULL_SUFFIX,
  FILTER_NULL_SUFFIX,
  FILTER_NUMBER_INVALID_TEXT,
  FILTER_OPERATORS,
  FILTER_OPERATOR_LABELS,
  FILTER_RANGE_END_SUFFIX,
  FILTER_RANGE_INVALID_TEXT,
  FILTER_RANGE_START_SUFFIX,
  FILTER_WIDGET_BY_TYPE,
  KEYWORD_FIELD,
  QUERY_COLLAPSE_THRESHOLD,
  QUERY_MAX_PER_ROW,
  QUERY_NARROW_BREAKPOINT,
  QUERY_SCHEME_SCOPES,
  QUERY_SCHEME_SCOPE_LABELS,
  QUERY_SCHEME_TARGETS,
  QUERY_SCHEME_TARGET_BUSINESS,
  SCHEME_DEFAULT_MAX,
  buildQueryParams,
  conditionText,
  defaultOperatorOf,
  fieldOf,
  filterActiveConditions,
  hasSchemeName,
  isConditionActive,
  normalizeConditions,
  normalizeSchemeEntry,
  normalizeSchemes,
  operatorsOf,
  pruneConditions,
  resolveDefaultScheme,
  resolveScheme,
  schemePriority,
  serializeCondition,
  serializeConditions,
  summarizeConditions,
  toConditionValue,
  validateConditionRange,
  type ConditionPruneResult,
  type ConditionSummary,
  type FilterCondition,
  type FilterField,
  type FilterFieldType,
  type FilterOption,
  type QuerySchemeEntry,
  type QuerySchemeScope,
  type QuerySchemeTarget,
} from './domain/filter'
export {
  STATUS_BULLET_SIZE,
  STATUS_BUILTIN_MAP,
  STATUS_FALLBACK_SEMANTIC,
  STATUS_FIXED_MAP,
  STATUS_SEMANTICS,
  STATUS_SEMANTIC_TOKENS,
  STATUS_SHAPES,
  describeStatus,
  isStatusSemantic,
  normalizeStatusColorMap,
  normalizeStatusValue,
  resolveStatusSemantic,
  resolveStatusText,
  statusTokenOf,
  type StatusDescription,
  type StatusResolveInput,
  type StatusSemantic,
  type StatusShape,
} from './domain/status'
export {
  NOTIFICATION_BADGE_MAX,
  NOTIFICATION_BATCH_MAX,
  NOTIFICATION_PAGE_SIZE_DEFAULT,
  NOTIFICATION_PAGE_SIZE_MAX,
  NOTIFICATION_POLL_INTERVAL,
  NOTIFICATION_READ_FILTERS,
  NOTIFICATION_RECENT_LIMIT,
  NOTIFICATION_TYPES,
  applyIncoming,
  applyOptimisticRead,
  applyOptimisticReadAll,
  applyOptimisticRemove,
  badgeTextOf,
  buildNotificationParams,
  clampBadgeCount,
  connectionLabel,
  countUnread,
  filterNotificationMessages,
  hasJumpTarget,
  isPollingNeeded,
  isUnread,
  jumpTargetOf,
  mergeMessages,
  messageTypeLabel,
  normalizeNotificationMessage,
  normalizeNotificationMessages,
  normalizeNotificationPage,
  parseUnreadCount,
  recentMessages,
  resolveMessageSemantic,
  restoreSnapshot,
  shouldPoll,
  shouldShowBadge,
  type NotificationConnectionState,
  type NotificationMessage,
  type NotificationMessageType,
  type NotificationPage,
  type NotificationQuery,
  type NotificationReadFilter,
  type NotificationRealtimePayload,
  type NotificationSnapshot,
} from './domain/notification'
export {
  METRIC_COMPACT_THRESHOLD,
  METRIC_COMPACT_UNITS,
  METRIC_COMPARE_KINDS,
  METRIC_COMPARE_LABELS,
  METRIC_EMPTY_TEXT,
  METRIC_FORMATS,
  METRIC_PRECISION_MAX,
  METRIC_TREND_DIRECTIONS,
  METRIC_TREND_PRECISION,
  SPARKLINE_DEFAULT_HEIGHT,
  SPARKLINE_DEFAULT_WIDTH,
  SPARKLINE_PADDING,
  buildSparkline,
  clampMetricRatio,
  compactMetricValue,
  formatMetricValue,
  interpolateMetricValue,
  isMetricEmpty,
  normalizeTrend,
  resolveMetricTrend,
  type MetricCompare,
  type MetricCompareKind,
  type MetricFormat,
  type MetricFormatOptions,
  type MetricTrend,
  type MetricTrendDirection,
  type SparklineGeometry,
} from './domain/metric'
export {
  LIST_DENSITIES,
  LIST_PREF_KEY_PREFIX,
  LIST_PREF_MAX_BYTES,
  LIST_PREF_MAX_CONDITIONS,
  buildListPrefKey,
  emptyListPreference,
  fromColumnPreferences,
  isListPreferenceOversized,
  listPreferenceBytes,
  normalizeListPreference,
  pruneListPreference,
  toColumnPreferences,
  trimListPreference,
  withQuery,
  withoutQuery,
  type ListColumnPreference,
  type ListDensity,
  type ListPreference,
  type ListPreferencePruneResult,
  type ListQueryPreference,
} from './domain/list-preference'
