from collections.abc import Iterable, Iterator, Mapping
from typing import TypeVar, overload

_KT = TypeVar("_KT")
_VT = TypeVar("_VT")

class SortedDict(dict[_KT, _VT]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, mapping: Mapping[_KT, _VT], /) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[tuple[_KT, _VT]], /) -> None: ...
    @overload
    def __init__(self, **kwargs: _VT) -> None: ...
    def get(self, key: _KT, default: _VT | None = ...) -> _VT | None: ...
    def __iter__(self) -> Iterator[_KT]: ...
    def __len__(self) -> int: ...
