from collections.abc import Iterable, Iterator, MutableSet
from typing import Self, TypeVar

_T = TypeVar("_T")

class SortedSet(MutableSet[_T]):
    def __init__(self, iterable: Iterable[_T] = ...) -> None: ...
    def add(self, value: _T) -> None: ...
    def discard(self, value: _T) -> None: ...
    def remove(self, value: _T) -> None: ...
    def clear(self) -> None: ...
    def __contains__(self, value: object) -> bool: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    def __and__(self, other: Iterable[_T]) -> Self: ...
    def __or__(self, other: Iterable[_T]) -> Self: ...
    def __sub__(self, other: Iterable[_T]) -> Self: ...
    def __xor__(self, other: Iterable[_T]) -> Self: ...
