from collections.abc import Callable, Iterable, Iterator, MutableSequence
from typing import TypeVar

_T = TypeVar("_T")

class SortedList(MutableSequence[_T]):
    def __init__(
        self,
        iterable: Iterable[_T] = ...,
        *,
        key: Callable[[_T], object] | None = ...,
    ) -> None: ...
    def add(self, value: _T) -> None: ...
    def update(self, iterable: Iterable[_T]) -> None: ...
    def discard(self, value: _T) -> None: ...
    def remove(self, value: _T) -> None: ...
    def clear(self) -> None: ...
    def __contains__(self, value: object) -> bool: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> _T: ...
    def __setitem__(self, index: int, value: _T) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def insert(self, index: int, value: _T) -> None: ...
