/**
 * 预置能力片段总出口（31 个，开放集合）：各域一目录、每片段一文件，此处统一出口。
 *
 * 引入本文件即在片段机制侧登记全部预置片段（`fragments.ts` 模块加载即 `registerKnownFragments`），
 * 组件按需组合片段：`import { useValue, useField } from '@/components/base'`。
 */

export * from './fragments'
export * from './access'
export * from './async-task'
export * from './column-config'
export * from './container'
export * from './design-token'
export * from './display'
export * from './display-control'
export * from './drag-drop'
export * from './dynamic-routes'
export * from './editor'
export * from './editor-kernel'
export * from './field'
export * from './field-perm'
export * from './field-shell'
export * from './form-container'
export * from './form-meta'
export * from './form-page'
export * from './fragment-context'
export * from './input'
export * from './input-control'
export * from './interactive'
export * from './layout'
export * from './locale'
export * from './media'
export * from './option-source'
export * from './persisted-state'
export * from './presigned-url'
export * from './query-scheme'
export * from './tabs'
export * from './tree'
export * from './tree-data'
export * from './upload-engine'
export * from './user-display'
export * from './value'
export * from './watermark'
